Implement SG workaround in Public cloud
outscale-dev/cloud-provider-osc pull request #129
Opened 2022-09-06 17:57 UTC by outscale-mdr

Close #68

2022-09-06 18:00 UTC, outscale-mdr commented
Need outscale-dev/osc-k8s-rke-cluster/pull/14

2022-09-07 07:35 UTC, outscale-mdr commented
Proof of success of the GH Action: https://github.com/outscale-mdr/cloud-provider-osc/runs/8211497738?check_suite_focus=true

2022-09-08 09:19 UTC, jerome-jutteau requested changes

2022-09-08 09:19 UTC, jerome-jutteau commented on tests/e2e/lb_crud.go
> +		ginkgo.By("Create Svc 1")
> Create Svc 1
to
> Create Svc 2

2022-09-16 08:56 UTC, outscale-mdr commented on tests/e2e/lb_crud.go
> +		ginkgo.By("Create Svc 1")
Thank you

2022-09-16 10:56 UTC, outscale-mdr commented
CI build failes due to CVE not code

2022-09-16 15:06 UTC, jerome-jutteau approved these changes

2022-09-26 14:26 UTC, closed without merging